blog/urls.py
from django.urls import path
from blog import views
from blog.views import article_category, article_detail, Index, CustomPageDetailView

urlpatterns = [
    path('', Index.as_view(), name='blog-home'),
    
    path('comments/', views.Comments, name='comments'),
    
    path('<slug:slug>/', article_category.as_view(), name='category'),
    
    path('legal/<slug:legalpageslug>/', views.CustomPageDetailView, name='legal-pages'),
    
    path('<slug:cat_slug>/<slug:slug>/', views.article_detail, name='article_detail'),

    
]

finalblogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog import views
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projectapp.urls')),
    
    # path('blog/', include('blog.urls')),
    # path('users/', include('users.urls')),
    # path('search/', views.search, name='search'),
    # path('summernote/', include('django_summernote.urls')),
    # path('trace/', include('traceapp.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog import views
from projectapp import views as pr_views
from django.conf.urls import url
urlpatterns = [
    path('', views.index, name="home-page"),
    path('summernote/', include('django_summernote.urls')),
    path('users/dashboard/', pr_views.staffdash, name="staff-dashboard"),
    # Staff Dashboard

    #####<<<<!-------Post Urls Starts Here------------>########

    path('users/create-post/', pr_views.CustomPostCreateView.as_view(), name="create-blog-post"),
    # Create the post
    path('users/posts/', pr_views.CustomPostView.as_view(), name="list-blog-post"),
    # List the post
    path('users/content/edit/<slug:cat_slug>/<slug:slug>/', pr_views.CustomPostEditView.as_view(), name="update"),
    # Update the post
    path('users/content/<slug:cat_slug>/<slug:slug>/delete/', pr_views.CustomPostDeleteView.as_view(), name="delete_post"),
    # Delete the post
    
    #####<<<<!-------Post Urls Ends Here------------>########


    #####<<<<!-------Page Urls Starts Here------------>########

    path('users/create-page/', pr_views.CustomPageCreateView.as_view(), name="create-page"), # Create Legal Page
    path('users/pages/', pr_views.CustomPageListView.as_view(), name="list-pages"), 
    # List Legal Pages
    path('users/content/legal/edit/<slug:legalpageslug>/', pr_views.CustomPageEditView.as_view(), name="update_legal_page"), 
    # Update Legal Pages
    path('users/content/legal/pages/<slug:legalpageslug>/delete/', pr_views.CustomPageDeleteView.as_view(), name="delete_legal_page"),
    # Delete the Legal Page

    #####<<<<!-------Page Urls Ends Here------------>########


    #####<<<<!-------Category Urls Starts Here------------>########

    path('users/create-category/', pr_views.CustomCategoryCreateView.as_view(), name="create-categories"),
    # Create a category
    path('users/categories/', pr_views.CustomCategoriesListView.as_view(), name="list-categories"),
    # List all categories
    path('users/category/edit/<slug:cat_slug>/', pr_views.CustomCategoryView.as_view(), name="update-categories"),
    # Update a category
    path('users/category/<slug:cat_slug>/delete/', pr_views.CustomCategoryDeleteView.as_view(), name="delete-categories"),
    # Delete a category

    #####<<<<!-------Category Urls Ends Here------------>########


    #####<<<<!-------Comments Urls Starts Here------------>########

    path('users/create-comments/', pr_views.CustomComentsCreateView.as_view(), name="create-comments"),

    # Create a comment
    path('users/comments/', pr_views.CustomCommentsView.as_view(), name="list-comments"),
    # List all the comments
    path('users/comments/edit/<slug:pk>/', pr_views.CustomCommentsEditView.as_view(), name="update"),
    #Update the comment
    path('users/comments/edit/<slug:pk>/delete/', pr_views.CustomCommentsDeleteView.as_view(), name="delete_comments"),
    # Delete comments

    #####<<<<!-------Comments Urls Ends Here------------>########

    path('users/create/group/', pr_views.CustomGroupCreateView.as_view(), name="create-group"),
    
    path('users/groups/', pr_views.CustomGroupListView.as_view(), name="list-group"),

    #####<<<<!-------Change user password Urls Starts Here------------>########

    path('users/change-password/', pr_views.CustomPasswordChangeView.as_view(), name="change-custom-user-password"),
    # Change user password

    #####<<<<!-------Change user password Urls Ends Here------------>########




    #####<<<<!-------Media gallery Urls Starts Here------------>########

    path('users/media-gallery/', pr_views.CustomMediaGallery.as_view(), name="list-media-gallery"),
    # List media

    path('users/media-gallery/upload/', pr_views.CustomMediaCreateView.as_view(), name="upload-media-gallery"),
    # Add media

    path('users/media-gallery/<slug:pk>/delete/', pr_views.CustomMediaDeleteView.as_view(), name="delete-media"),
    # Delete media

    #####<<<<!-------Media gallery Urls Ends Here------------>########




    #####<<<<!-------User Urls Starts Here------------>########

    path('users/list/', pr_views.AllUsersList.as_view(), name='list-users'),
    # List Users

    path('user/<int:pk>/edit/', pr_views.CustomUserEditView.as_view(), name='update-user'),
    # Update user

    path('edit/user/<int:pk>/', pr_views.ClientUserEditView.as_view(), name='client-update-user'),
    # Client user edit

    path('user/<int:pk>/delete/', pr_views.CustomUserDeleteView.as_view(), name='delete-user'),
    # Delete user

    #####<<<<!-------User Urls Ends Here------------>########



    path('blog/', include('blog.urls')),

    path('users/', include('users.urls')),

    path('user/update/profile/<int:pk>', pr_views.ProfileUpdateView.as_view(), name='update-user-profile'),

    path('search/', views.search, name='search'),
    
    path('category/create/', pr_views.CategoryCreatePopup, name = "CategoryCreate"),

    # path('trace/', include('traceapp.urls')),
    # url(r'^filer/', include('filer.urls')),
    # path('user/add/', pr_views.CustomUserCreateView.as_view(), name='add-user'),


    # url(r'^category/create', pr_views.CategoryCreatePopup, name = "CategoryCreate"),


    # url(r'^category/(?P<pk>\d+)/edit', pr_views.CategoryEditPopup, name = "CategoryEdit"),
    # url(r'^category/ajax/get_category_id', pr_views.get_category_id, name = "get_category_id"),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from users.models import User
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
import datetime



class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(created_date__lte=datetime.datetime.today())

class CommentsManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(CommentsManager, self).filter(draft=False)


class Category(models.Model):
    category = models.CharField(max_length=50, default='', unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    draft = models.BooleanField(default=False)
    description = models.TextField(default="", null=True, blank=True)
    author = models.ForeignKey(User, default="", on_delete=models.CASCADE)
    objects = CommentsManager()
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category

    def get_absolute_url(self):
        return reverse("category", kwargs={'slug' : self.slug})

class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=160, default='', null=False)
    category = models.ForeignKey(Category, default=None, on_delete=models.CASCADE)
    content = models.TextField(default="")
    slug = models.SlugField(max_length=200, unique=True)
    draft = models.BooleanField(default=False)
    created_date = models.DateField(null=True, auto_now_add=False)
    updated = models.DateField(blank=True, null=True)
    featured_image = models.ImageField(upload_to="img/featured_image", default="")
    author = models.ForeignKey(User, default="", on_delete=models.CASCADE)
    objects = PostManager()
    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article_detail", kwargs={
                        "cat_slug": self.category.slug, 
                        "slug": self.slug
            }
        )


class BlogComments(models.Model):
    serial_key = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    comment_parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    draft = models.BooleanField(default=False)
    time = models.DateField(default=datetime.datetime.today)
    objects = CommentsManager()
    # published = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
    def __str__(self):
        return self.comment[0:15] + '...' + ' by ' + self.user.first_name + ' on ' + self.post.title


class LegalPages(models.Model):
    title = models.CharField(max_length=70, default='')
    content = models.TextField(default="")
    # content = SummernoteTextField(default="")
    created_date = models.DateField(default=datetime.datetime.today)
    featured_image = models.ImageField(upload_to="img/featured_image", default="")
    author = models.ForeignKey(User, default="", on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("legal-pages", kwargs={
                        "legalpageslug": self.slug
            }
        )


@receiver(post_delete)
def delete_files_when_row_deleted_from_db(sender, instance, **kwargs):
    for field in sender._meta.concrete_fields:
        if isinstance(field,models.ImageField):
            instance_file_field = getattr(instance,field.name)
            delete_file_if_unused(sender,instance,field,instance_file_field)

@receiver(pre_save)
def delete_files_when_file_changed(sender,instance, **kwargs):
    if not instance.pk:
        return
    for field in sender._meta.concrete_fields:
        if isinstance(field,models.ImageField):
            try:
                instance_in_db = sender.objects.get(pk=instance.pk)
            except sender.DoesNotExist:
                return
            instance_in_db_file_field = getattr(instance_in_db,field.name)
            instance_file_field = getattr(instance,field.name)
            if instance_in_db_file_field.name != instance_file_field.name:
                delete_file_if_unused(sender,instance,field,instance_in_db_file_field)
  
def delete_file_if_unused(model,instance,field,instance_file_field):
    dynamic_field = {}
    dynamic_field[field.name] = instance_file_field.name
    other_refs_exist = model.objects.filter(**dynamic_field).exclude(pk=instance.pk).exists()
    if not other_refs_exist:
        instance_file_field.delete(False)

projectapp/models.py
from django.db import models

# Create your models here.

projectapp/forms.py
from django.contrib.auth.models import Group, User
from django import forms
from django.forms import fields
from django.utils import timezone
from blog.models import BlogComments, Post, Category, LegalPages
from django_summernote.widgets import SummernoteWidget
from mediagallery.models import MediaGallery
from users.models import UserProfile


class CreatePostForm(forms.ModelForm):
    created_date = forms.DateField(
        widget=forms.widgets.SelectDateWidget(), 
        required=False,
        label="Created Date"
        )
    content = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model = Post
        fields = ['title','category', 'content', 'slug', 'featured_image', 'created_date', 'author', 'draft']

class UpdatePostForm(forms.ModelForm):
    updated = forms.DateField(
        widget=forms.widgets.SelectDateWidget(), 
        required=False
        )
    content = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model = Post
        fields = ['title','category', 'content', 'slug', 'featured_image', 'updated', 'author', 'draft']
class StaffUpdatePostForm(forms.ModelForm):
    updated = forms.DateField(
        widget=forms.widgets.SelectDateWidget(), 
        required=False
        )
    content = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model = Post
        fields = ['title','category', 'content', 'slug', 'featured_image', 'updated']

class CreatePageForm(forms.ModelForm):
    created_date = forms.DateField(
        widget=forms.widgets.SelectDateWidget(), 
        required=False
        )
    content = forms.CharField(widget=SummernoteWidget())

    class Meta:
        model = LegalPages
        fields = ['title', 'content', 'slug', 'featured_image', 'created_date', 'author']


class CreateCategoryForm(forms.ModelForm):
    description = forms.CharField(widget=SummernoteWidget(), required=False)
    class Meta:
        model = Category
        fields = ['category', 'slug', 'description', 'author', 'draft']

class CreateBlogCommentsForm(forms.ModelForm):
    time = forms.DateTimeField(
        label='Date',
        widget=forms.widgets.DateTimeInput(attrs={'type':'datetime-local'})
    )
    class Meta:
        model = BlogComments
        fields = ['user', 'post', 'comment', 'comment_parent', 'time', 'draft']
class UpdateBlogCommentsForm(forms.ModelForm):
    class Meta:
        model = BlogComments
        fields = ['user', 'post', 'comment', 'comment_parent','draft']
class StaffUpdateBlogCommentsForm(forms.ModelForm):
    class Meta:
        model = BlogComments
        fields = ['post', 'comment',]

class MediaCreateForm(forms.ModelForm):
    class Meta:
        model = MediaGallery
        fields = '__all__'

class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        date = forms.DateTimeInput()
        fields = [
            'first_name',
            'last_name',
            'email',
            'is_staff',
            'is_active',
            'is_superuser',
            'groups',
        ]

class ClientUserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        # fields = "__all__"
        fields = [
            'first_name',
            'last_name',
            'email',            
        ]

class CustomUserGroup(forms.ModelForm):
    class Meta:
        model = Group
        fields = "__all__"

class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']

projectapp/templates/projectapp/categorylist.html
{% extends 'projectapp/base.html' %}
{% load static %}

{% block content %}

<div class="page-wrapper">

    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">All Categories ({{counts}})</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Library</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">

                        <div class="row">
                            <h4 class="card-title m-b-0 col-6">Recent {{create}}s</h4>
                            <span class="col-6">
                                <a href="{% url 'create-categories' %}" class="btn btn-primary text-right">
                                    Create a New Category
                                </a>
                            </span>
                        </div>
                    </div>
                    
                    <div class="comment-widgets scrollable">
                        <!-- Comment Row -->
                        {% for post,count in category %}
                        {% comment %} {% for post,count in category %} {% endcomment %}
                        <div class="d-flex flex-row comment-row m-t-0 border border-success">
                            
                            <div class="comment-text w-100">
                                
                                <a href="/users/category/edit/{{post.slug}}/">
                                    <h6 class="font-medium">{{post.category}} ({{count.post_count}})</h6>
                                </a>
                                
                                <span class="m-b-15 d-block">{{post.description|striptags|slice:':200'|safe}}...</span>
                                <div class="comment-footer">

                                    {% if post.draft %}
                                    <span class="text-danger float-right">Draft</span><br>
                                    {% else %}
                                    <span class="text-warning float-right">Published</span><br>
                                    {% endif %}





                                    {% comment %} <span class="text-warning float-right">Published on: {{post.created_date}}</span><br>
                                    <span class="text-success float-right">Updated on: {{post.updated}}</span> {% endcomment %}
                                    {% if user.is_superuser %}
                                    <a href="/users/category/edit/{{post.slug}}/">
                                        <button type="button" class="btn btn-cyan btn-sm">Edit</button>
                                    </a>
                                    <a href="/users/category/{{post.slug}}/delete/">
                                        <button type="button" class="btn btn-danger btn-sm">Delete</button>
                                    </a>
                                    {% endif %}
                                    <a href="{{post.get_absolute_url}}" target="_blank">
                                        <button type="button" class="btn btn-success btn-sm">View Post</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
                <!-- accoridan part -->

                <!-- toggle part -->

            </div>


        </div>
    </div>
</div>

{% endblock content %}

projectapp/templates/projectapp/commentlist.html
{% extends 'projectapp/base.html' %}
{% load static %}

{% block content %}

<div class="page-wrapper">

    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">All {{create}}s</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Library</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">

                        <div class="row">
                            <h4 class="card-title m-b-0 col-6">Recent {{create}}s</h4>
                            <span class="col-6">
                                <a href="{% url 'create-comments' %}" class="btn btn-primary text-right">
                                    Create a New {{created}}
                                </a>
                            </span>
                        </div>
                    </div>
                    
                    <div class="comment-widgets scrollable">
                        <!-- Comment Row -->
                        {% for post in post %}
                        <div class="d-flex flex-row comment-row m-t-0 border border-success">
                            
                            <div class="comment-text w-100">
                                <a href="/users/comments/edit/{{post.pk}}/">
                                    <h6 class="font-medium">{{post.comment|truncatechars:150}}</h6>
                                </a>
                                <span class="m-b-15 d-block">
                                    on <a href="{{post.post.get_absolute_url}}" target="_blank">{{post.post.title}}</a>
                                </span>
                                {% if post.serial_key %}
                                    {% if post.comment_parent %}
                                    <span class="m-b-15 d-block">
                                        Reply to: <a href="/users/comments/edit/{{post.comment_parent.pk}}/" target="_blank">{{post.comment_parent}}</a>
                                    </span>
                                    {% endif %}
                                {% endif %}
                                <div class="comment-footer">


                                    {% if post.draft %}
                                    <span class="text-danger float-right">Draft</span><br>
                                    {% else %}
                                    <span class="text-warning float-right">Published on:
                                        {{post.time}}</span><br>
                                    {% endif %}
                                    
                                    
                                    <a href="/users/comments/edit/{{post.pk}}/">
                                        <button type="button" class="btn btn-cyan btn-sm">Edit</button>
                                    </a>
                                    <a href="/users/comments/edit/{{post.pk}}/delete/">
                                        <button type="button" class="btn btn-danger btn-sm">Delete</button>
                                    </a>
                                    
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
                

            </div>


        </div>
    </div>
</div>

{% endblock content %}

projectapp/templates/projectapp/postlist.html
{% extends 'projectapp/base.html' %}
{% load static %}

{% block content %}
        <div class="page-wrapper">

            <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">All Posts ({{post.count}})</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{% url 'staff-dashboard' %}">Dashboard</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Posts</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container-fluid">

                <div class="row">
                    <div class="col-12">
                        
                        
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Recent Posts</h5>
                            </div>
                            <div class="m-4">
                              <a href="{% url 'create-blog-post' %}" class="btn btn-primary">Create a new post</a>
                            </div>
                            <div class="table-responsive">
                            <table id="zero_config" class="table table-striped table-bordered">
                              <thead>
                                <tr>
                                  <th scope="col">SN</th>
                                  <th scope="col">Title</th>
                                  <th scope="col">Author</th>
                                  <th scope="col">Category</th>
                                  <th scope="col">Comments</th>
                                  <th scope="col">Published</th>
                                  <th scope="col">Draft</th>
                                  <th scope="col">SEO Title</th>
                                  <th scope="col">SEO Description</th>
                                  <th scope="col">Featured Image</th>
                                </tr>
                              </thead>

                              <tbody>
                                {% for post in post %}

                                <tr>

                                  <th scope="row">{{forloop.counter}}.</th>

                                  <td>
                                        <h6>
                                          <a href="/users/content/edit/{{post.category.slug}}/{{post.slug}}/" class="text-primary">{{post.title}}</a>
                                          </h6>
                                        <br></br>
                                        <div class="flex">
                                        <a href="/users/content/edit/{{post.category.slug}}/{{post.slug}}/" class="btn btn-primary btn-sm mt-1">Edit</a>

                                        <a href="/users/content/{{post.category.slug}}/{{post.slug}}/delete/" class="btn btn-danger btn-sm mt-1">Delete</a>

                                        <a href="{{post.get_absolute_url}}" target="_blank" class="btn btn-success btn-sm mt-1">View</a>
                                      </div>


                                  </td>


                                  <td>{{post.author.first_name}} {{post.author.last_name}}</td>

                                  <td>
                                    <a href="/users/category/edit/{{post.category.slug}}/">
                                      {{post.category}}
                                    </a>
                                  </td>
                                  <td>
                                      <a class="text-white btn btn-primary btn-sm">{{post.blogcomments_set.count}}</a>
                                  </td>
                                  {% if post.draft %}
                                  <td>
                                      <a class="text-white btn btn-danger btn-sm">No</a>
                                  </td>
                                  {% else %}
                                    <td>
                                      <a class="text-white btn btn-success btn-sm">Yes</a>
                                    </br> <br>
                                      <p>Date: {{post.created_date}}</p>
                                    </td>
                                  {% endif %}

                                  {% if post.draft %}
                                  <td>
                                    <a class="text-white btn btn-danger btn-sm">Yes (PO)</a>
                                  </td>
                                  {% elif post.category.draft %}
                                  <td>
                                    <a class="text-white btn btn-danger btn-sm">Yes (CA)</a>
                                  </td>
                                  {% else %}
                                    <td>
                                      <a class="text-white btn btn-success btn-sm">No</a>
                                    </td>
                                  {% endif %}
                                  <td>{{post.title}}</td>
                                  <td>{{post.slug}}</td>
                                  <td>
                                    <a href="{{post.featured_image.url}}" target="_blank">
                                    <div class="p-2 border border-danger">
                                        {{post.featured_image.url|truncatechars:20}}
                                      </div>
                                    </a>
                                    
                                  </td>

                                </tr>

                                {% endfor %}
                                
                              </tbody>

                            </table>
                        </div>
                        </div>
                      
                    </div>
                </div>

            </div>         

            {% endblock content %}